### ISSUE TITLE
Add test framework

### ISSUE THREAD

**Issue by Kornil** [Kornil/simple-react-app#3]
Ideally Jest and Enzyme.

**Comment by andrerfneves** [comment]
Hey @Kornil I use your package for some side projects of mine. Happy to help setup Jest and all that. Do you have an ongoing PR/WIP for this or can I start from `scratch` on this? Do you have a specific folder structure that you prefer for testing or can I follow my best practices? 👍

**Comment by Kornil** [comment]
I have yet to start on this, my idea was to follow jest convention of having a `__tests__` folder, the official jest examples offer insights on this.
Naming convention is explained here http://facebook.github.io/jest/docs/en/configuration.html#testregex-string if you need any help feel free to reach out!

**Comment by andrerfneves** [comment]
@Kornil sounds good to me. I'll get something up in the next week or so. Thanks

**Comment by Kornil** [comment]
I'm sorry @andrerfneves I thought you were gone :(
There's still a lot of room for improvement on the testing framework, and I still need someone to review it (I'm not the best at testing), willing to give a hand? 💃

**Comment by andrerfneves** [comment]
Yeah absolutely. Can spend some time testing it on the weekend. OSS is always an iterative process anyways! Thanks for doing this. You can close this issue. If there's anything to raise I'll create a new issue! Cheers man

**Comment by Kornil** [comment]
Thank you for your help!
I'll close this issue but feel free to open a new one with bugs/improvements for the testing framework when you get the time!
I'll be travelling this weekend so I'll probably only see it on Monday, do your worst!
