### ISSUE TITLE
Rewrite App.jsx as dumb component

### ISSUE THREAD

**Issue by Kornil** [Kornil/simple-react-app#6]
At the moment `App.jsx` main component is written as a class, since it does not use state, it could potentially be rewritten as a simple ES6 functional component.

I'm open to help anyone who wants to take this issue as first one to learn about React.

**Comment by tomhoad** [comment]
#13 submitted!

**Comment by TENsaga** [comment]
#14  Gave it a go. Regardless, thanks for the Git lesson Kornil.
